#!/bin/bash
set -o nounset -o errexit -o pipefail

##Install VSCode and requirements including Node
apt-get update -qq && \
#curl -fsSL https://deb.nodesource.com/setup_14.x | bash - && \
apt-get install \
  jq && \
#  libx11-dev \
#  libxkbfile-dev \
#  libsecret-1-dev \
#  node-gyp \
#  nodejs -y && \
pip install -q python-language-server autopep8 flake8 pylint && \
apt-get clean && \
rm -rf \
  /tmp/* \
  /var/lib/apt/lists/* \
  /var/tmp/*

CODE_SERVER_VERSION=3.12.0

curl -L https://github.com/cdr/code-server/releases/download/v${CODE_SERVER_VERSION}/code-server_${CODE_SERVER_VERSION}_amd64.deb -o /tmp/code-server.deb
dpkg -i /tmp/code-server.deb
rm -rf /tmp/*

#Install VSCode extensions for python (pinned to this version due to a bug)
cd /tmp && \
mkdir -p /home/ubuntu/.local/share/code-server/ && \
mkdir -p /home/ubuntu/.local/share/code-server/User && \
echo "{\"extensions.autoCheckUpdates\": false, \"extensions.autoUpdate\": false}" > /home/ubuntu/.local/share/code-server/User/settings.json && \
wget https://github.com/microsoft/vscode-python/releases/download/2021.3.680753044/ms-python-release.vsix \
 && code-server --install-extension ./ms-python-release.vsix --extensions-dir /home/ubuntu/.local/share/code-server/extensions || true
chown -R ubuntu:ubuntu /home/ubuntu/.local/ && \
rm -rf /tmp/*
